apiVersion: nfspvc.dana.io/v1alpha1
kind: NfsPvc
metadata:
  labels:
    app.kubernetes.io/name: test1
    app.kubernetes.io/instance: test1
    app.kubernetes.io/part-of: nfspvc-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: nfspvc-operator
  name: test4
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
      storage: 200G
  path: /noki
  server: vs-nas-noki
  nfsVersion: v4
